'use client';

import { useState, useCallback } from 'react';
import Link from 'next/link';
import { useTheme } from '../theme-provider';
import Script from "next/script";
import Head from "next/head";

export const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is strikethrough text?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Strikethrough text is text with a horizontal line drawn through its center, like t̶h̶i̶s̶. It is used to indicate deleted, corrected, or ironic content.",
      },
    },
    {
      "@type": "Question",
      name: "How does the strikethrough text generator work?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The generator uses Unicode combining characters — specifically the combining long stroke overlay (U+0336) — that are added to each letter, creating a strikethrough effect that works anywhere Unicode text is supported.",
      },
    },
    {
      "@type": "Question",
      name: "Where can I use strikethrough text?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "You can use strikethrough text on Twitter/X, Facebook, Instagram, Discord, WhatsApp, Reddit, Telegram, and anywhere that renders Unicode. It works in plain text fields that do not support markdown.",
      },
    },
    {
      "@type": "Question",
      name: "Is this different from HTML strikethrough?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. HTML uses the <s> or <del> tag which only works in web pages. Unicode strikethrough works in plain text, social media posts, messages, and anywhere you can paste text.",
      },
    },
    {
      "@type": "Question",
      name: "Can I use strikethrough in Discord?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. Discord supports both the native ~~tilde~~ markdown syntax and Unicode strikethrough characters generated by this tool. Unicode strikethrough also works in usernames and nicknames where markdown is not supported.",
      },
    },
  ],
};

export const webAppSchema = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Strikethrough Text Generator",
  url: "https://convertcase.in/strikethrough-text-generator",
  description: "Generate strikethrough text using Unicode combining characters. Works on Twitter, Discord, WhatsApp, Instagram, and any plain-text field.",
  applicationCategory: "UtilityApplication",
  operatingSystem: "All",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

export const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://convertcase.in",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Strikethrough Text Generator",
      item: "https://convertcase.in/strikethrough-text-generator",
    },
  ],
};

export const strikethroughMeta = {
  title: 'Strikethrough Text Generator — Cross Out Text Online (Free)',
  description:
    'Free online strikethrough text generator. Cross out any text using Unicode combining characters. Works on Twitter, Discord, WhatsApp, Instagram, and all plain-text fields.',
  keywords: [
    'strikethrough text generator',
    'cross out text online',
    'strikethrough unicode',
    'strike through text copy paste',
    'strikethrough for twitter',
    'discord strikethrough text',
  ],
  alternates: { canonical: 'https://convertcase.in/strikethrough-text-generator' },
  openGraph: {
    title: 'Strikethrough Text Generator — ConvertCase',
    description: 'Cross out text with Unicode strikethrough. Works everywhere. Free & no ads.',
    url: 'https://convertcase.in/strikethrough-text-generator',
  },
};

// Unicode combining strikethrough character
const COMBINING_LONG_STROKE = '\u0336';
// Double strikethrough uses combining double tilde
const COMBINING_DOUBLE_TILDE = '\u0334';
// Combining short stroke overlay
const COMBINING_SHORT_STROKE = '\u0335';

function applyStrikethrough(text: string, combiner: string): string {
  return text
    .split('')
    .map((char) => (char === '\n' || char === ' ' ? char : char + combiner))
    .join('');
}

function getStats(text: string) {
  return {
    characters: text.length,
    words: text.trim() === '' ? 0 : text.trim().split(/\s+/).length,
    lines: text === '' ? 0 : text.split('\n').length,
  };
}

const STYLES = [
  {
    id: 'long',
    label: 'S̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶',
    name: 'Strikethrough',
    desc: 'Classic single line through the center of each character.',
    combiner: COMBINING_LONG_STROKE,
    unicode: 'U+0336',
  },
  {
    id: 'short',
    label: 'S̵t̵r̵i̵k̵e̵t̵h̵r̵o̵u̵g̵h̵',
    name: 'Short Stroke',
    desc: 'A shorter stroke overlay. Appears slightly different across fonts.',
    combiner: COMBINING_SHORT_STROKE,
    unicode: 'U+0335',
  },
  {
    id: 'tilde',
    label: 'S̴t̴r̴i̴k̴e̴t̴h̴r̴o̴u̴g̴h̴',
    name: 'Tilde Overlay',
    desc: 'A wavy tilde through each character. Creates a distinct, expressive look.',
    combiner: COMBINING_DOUBLE_TILDE,
    unicode: 'U+0334',
  },
];

export default function StrikethroughTextGenerator() {
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  const [input, setInput] = useState('');
  const [selectedStyle, setSelectedStyle] = useState(STYLES[0]);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const { characters, words, lines } = getStats(input);

  const surface = isDark ? '#111827' : '#fff';
  const borderColor = isDark ? '#1f2937' : '#e2e8f0';
  const borderStyle = `1px solid ${borderColor}`;
  const textPrimary = isDark ? '#f1f5f9' : '#0f172a';
  const textMuted = isDark ? '#94a3b8' : '#64748b';

  const handleConvert = useCallback(() => {
    setOutput(
      input
        .split('\n')
        .map((line) => applyStrikethrough(line, selectedStyle.combiner))
        .join('\n')
    );
  }, [input, selectedStyle]);

  const handleCopy = useCallback(async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [output]);

  const handleDownload = useCallback(() => {
    if (!output) return;
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'strikethrough-text.txt';
    a.click();
    URL.revokeObjectURL(url);
  }, [output]);

  const handleClear = useCallback(() => {
    setInput('');
    setOutput('');
  }, []);

  const relatedTools = [
    { href: '/', icon: 'Cc', title: 'Convert Case', desc: 'All-in-one text case converter.' },
    { href: '/invisible-text-generator', icon: '​​​​​​​​​', title: 'Invisible Text Generator', desc: 'Copy blank Unicode characters.' },
    { href: '/pascal-case-converter', icon: 'Pc', title: 'Pascal Case Converter', desc: 'Convert text to PascalCase.' },
    { href: '/camel-case-converter', icon: 'cC', title: 'Camel Case Converter', desc: 'Convert text to camelCase format.' },
    { href: '/snake-case-converter', icon: 'sc', title: 'Snake Case Converter', desc: 'Convert text to snake_case format.' },
    { href: '/title-case-converter', icon: 'Tt', title: 'Title Case Converter', desc: 'Capitalize every word instantly.' },
  ];

  return (
    <>
      <Head>
        <Script
          id="faq-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
        <Script
          id="webapp-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
        />
        <Script
          id="breadcrumb-schema"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
        />
      </Head>
      <main
        className="min-h-screen px-4 py-12"
        style={{
          paddingTop: 'calc(56px + 2.5rem)',
          background: isDark ? '#030712' : '#f8fafc',
          color: isDark ? '#fff' : '#0f172a',
          transition: 'background 0.3s, color 0.3s',
        }}
      >
        <div className="max-w-3xl mx-auto">

          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-2xl font-semibold mb-2">Strikethrough Text Generator</h1>
            <p className="text-sm" style={{ color: textMuted }}>
              Cross out any text using Unicode combining characters. Works in plain-text fields on{' '}
              <code>Twitter</code>, <code>Discord</code>, <code>WhatsApp</code>, <code>Instagram</code>, and everywhere else — no markdown needed.
            </p>
          </div>

          {/* Style Selector */}
          <div className="rounded-xl border mb-3" style={{ background: surface, borderColor, boxShadow: isDark ? 'none' : '0 1px 8px rgba(0,0,0,0.06)' }}>
            <label className="block px-4 pt-3 text-xs font-semibold" style={{ color: textMuted }}>STRIKETHROUGH STYLE</label>
            <div className="p-4 pt-2 grid grid-cols-1 sm:grid-cols-3 gap-2">
              {STYLES.map((style) => (
                <button
                  key={style.id}
                  onClick={() => setSelectedStyle(style)}
                  className="flex flex-col items-start gap-1 rounded-lg p-3 text-left transition"
                  style={{
                    background: selectedStyle.id === style.id
                      ? (isDark ? '#1e1b4b' : '#eef2ff')
                      : (isDark ? '#0d1117' : '#f8fafc'),
                    border: `1px solid ${selectedStyle.id === style.id ? '#6366f1' : borderColor}`,
                    color: textPrimary,
                  }}
                >
                  <span className="text-base font-medium" style={{ fontFamily: '"Courier New", monospace', color: selectedStyle.id === style.id ? '#6366f1' : textPrimary }}>
                    {style.label}
                  </span>
                  <span className="text-xs" style={{ color: textMuted }}>{style.name}</span>
                  <code className="text-xs" style={{ color: isDark ? '#4b5563' : '#94a3b8' }}>{style.unicode}</code>
                </button>
              ))}
            </div>
          </div>

          {/* Input */}
          <div className="rounded-xl border mb-3" style={{ background: surface, borderColor, boxShadow: isDark ? 'none' : '0 1px 8px rgba(0,0,0,0.06)' }}>
            <label className="block px-4 pt-3 text-xs font-semibold" style={{ color: textMuted }}>INPUT</label>
            <textarea
              className="w-full bg-transparent placeholder-gray-500 p-4 pt-2 text-sm rounded-xl resize-none focus:outline-none"
              rows={6}
              placeholder="Type or paste your text here"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              style={{ color: isDark ? '#f1f5f9' : '#0f172a' }}
            />
            <div className="flex items-center justify-between px-4 pb-3">
              <button onClick={handleClear} title="Clear" className="p-2 rounded-lg transition" style={{ color: textMuted }}>
                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6M9 7h6m2 0H7m2-3h6a1 1 0 011 1v1H8V5a1 1 0 011-1z" />
                </svg>
              </button>
              <p className="text-xs" style={{ color: isDark ? '#4b5563' : '#94a3b8' }}>
                Characters: {characters} &nbsp;|&nbsp; Words: {words} &nbsp;|&nbsp; Lines: {lines}
              </p>
            </div>
          </div>

          {/* Convert Button */}
          <button
            onClick={handleConvert}
            className="w-full py-3 rounded-xl text-sm font-semibold mb-3 transition hover:brightness-110"
            style={{
              background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #ec4899 100%)',
              color: '#fff',
              boxShadow: '0 2px 12px rgba(99,102,241,0.35)',
            }}
          >
            Add Strikethrough →
          </button>

          {/* Output */}
          <div className="rounded-xl border" style={{ background: surface, borderColor, boxShadow: isDark ? 'none' : '0 1px 8px rgba(0,0,0,0.06)' }}>
            <label className="block px-4 pt-3 text-xs font-semibold" style={{ color: textMuted }}>
              OUTPUT — {selectedStyle.name.toUpperCase()} ({selectedStyle.unicode})
            </label>
            <textarea
              className="w-full bg-transparent p-4 pt-2 text-sm rounded-xl resize-none focus:outline-none"
              rows={6}
              readOnly
              placeholder="Your strikethrough text will appear here"
              value={output}
              style={{ color: isDark ? '#f1f5f9' : '#0f172a', fontFamily: '"Courier New", monospace' }}
            />
            <div className="flex items-center px-4 pb-3 gap-2">
              <button onClick={handleCopy} title="Copy" className="p-2 rounded-lg transition" style={{ color: textMuted }}>
                {copied ? (
                  <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-4 10h6a2 2 0 002-2v-8a2 2 0 00-2-2h-6a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                )}
              </button>
              <button onClick={handleDownload} title="Download" className="p-2 rounded-lg transition" style={{ color: textMuted }}>
                <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4" />
                </svg>
              </button>
            </div>
          </div>

          {/* Example */}
          <div className="rounded-xl border mt-4 p-4" style={{ background: isDark ? '#0d1117' : '#f1f5f9', borderColor }}>
            <p className="text-xs font-semibold mb-2" style={{ color: textMuted }}>EXAMPLE</p>
            <div className="flex flex-col gap-1 text-sm" style={{ fontFamily: '"Courier New", monospace' }}>
              <p style={{ color: textMuted }}>Input: &nbsp;&nbsp;<span style={{ color: textPrimary }}>"hello world"</span></p>
              <p style={{ color: textMuted }}>Output: <span style={{ color: '#6366f1' }}>h̶e̶l̶l̶o̶ w̶o̶r̶l̶d̶</span></p>
            </div>
          </div>

          {/* Related Tools */}
          <section className="pt-12 pb-16" aria-labelledby="related-heading">
            <h2 id="related-heading" className="text-lg font-semibold mb-4 pb-3" style={{ color: textPrimary, borderBottom: borderStyle }}>Related Tools</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {relatedTools.map(({ href, icon, title, desc }) => (
                <Link key={href} href={href} className="flex items-center gap-3 rounded-lg p-4 no-underline transition hover:-translate-y-0.5" style={{ background: surface, border: borderStyle, color: 'inherit' }}>
                  <span className="w-10 h-10 min-w-10 rounded-lg flex items-center justify-center text-xs font-bold font-mono" style={{ background: isDark ? '#1f2937' : '#f1f5f9', border: `1px solid ${isDark ? '#374151' : '#e2e8f0'}`, color: textMuted }}>{icon}</span>
                  <div>
                    <strong className="block text-sm mb-0.5" style={{ color: textPrimary }}>{title}</strong>
                    <p className="text-xs m-0" style={{ color: textMuted }}>{desc}</p>
                  </div>
                </Link>
              ))}
            </div>
          </section>

          {/* About / FAQ */}
          <section className="pb-16" aria-labelledby="faq-heading">
            <h2 id="faq-heading" className="text-lg font-semibold mb-4 pb-3" style={{ color: textPrimary, borderBottom: borderStyle }}>About Strikethrough Text</h2>
            <div style={{ color: textMuted, fontSize: '0.875rem', lineHeight: '1.75' }}>
              <p style={{ marginBottom: '1rem' }}>
                <strong style={{ color: textPrimary }}>Strikethrough text</strong> is created by adding Unicode combining characters — specifically the <strong style={{ color: textPrimary }}>Combining Long Stroke Overlay (U+0336)</strong> — after each letter. Unlike HTML's <code>&lt;s&gt;</code> tag or markdown's <code>~~tilde~~</code> syntax, Unicode strikethrough works in any plain-text field.
              </p>
              <h3 style={{ color: textPrimary, fontWeight: 600, marginBottom: '0.5rem' }}>Where does strikethrough text work?</h3>
              <ul style={{ paddingLeft: '1.25rem', marginBottom: '1rem', listStyleType: 'disc' }}>
                <li>Twitter/X posts and bios</li>
                <li>Discord messages, usernames, and nicknames</li>
                <li>WhatsApp and Telegram messages</li>
                <li>Instagram captions and bios</li>
                <li>Facebook posts and comments</li>
                <li>Reddit comments and posts</li>
                <li>Any input field that supports Unicode</li>
              </ul>
              <h3 style={{ color: textPrimary, fontWeight: 600, marginBottom: '0.5rem' }}>Which strikethrough style should I use?</h3>
              <p style={{ marginBottom: '1rem' }}>
                The <strong style={{ color: textPrimary }}>Strikethrough (U+0336)</strong> is the most widely recognised and renders consistently across devices. The <strong style={{ color: textPrimary }}>Tilde Overlay (U+0334)</strong> has a creative, wavy look that stands out in social posts. The <strong style={{ color: textPrimary }}>Short Stroke (U+0335)</strong> is more subtle and font-dependent.
              </p>
              <h3 style={{ color: textPrimary, fontWeight: 600, marginBottom: '0.5rem' }}>How is this different from markdown strikethrough?</h3>
              <p>Markdown <code>~~text~~</code> only works in apps that parse markdown (Discord messages, Reddit, some editors). Unicode strikethrough is embedded in the characters themselves, so it displays correctly everywhere — even in plain text fields, email subjects, and app names.</p>
            </div>
          </section>

        </div>
      </main>
    </>
  );
}